<%@ include file="userCommonHeader.jsp"%>

<div class="container" style="background:white;padding:25px;">
<div class="container-fluid">
					<div class="panel panel-success">
					<div class="panel-heading">Terms &amp; Conditions</div>
	             	<div class="panel-body">
	             	
	             	<p>This document is an electronic
				record in terms of the Information Technology Act, 2000 and rules
				there under pertaining to electronic records as applicable and
				amended. This electronic record is generated by a computer system
				and does not require any physical or digital signatures. 
				This document is published in accordance with the provisions of Rule 3
				(1) of the Information Technology (Intermediaries Guidelines) Rules,
				2011 that require publishing the rules and regulations, privacy
				policy and the terms and conditions for access or usage of
				www.bharatmatrimony.com (the "Website").</p>
				
				<p> Please read the following
				terms and conditions very carefully as your use of the Website and
				associated BM Services (as defined below) is subject to your
				acceptance of and compliance with the following terms and conditions
				including the applicable policies which are incorporated herein by
				way of reference and as amended from time to time (the "Terms and
				conditions"). </p>
			<p>	ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE
				INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS herein, SO
				PLEASE READ THE TERMS and conditions CAREFULLY BEFORE PROCEEDING. By
				impliedly or expressly accepting these Terms and Conditions of use
				of website, You also accept and agree that you have read, understood
				and are bound by these Terms and conditions, regardless of how
				you/BM member subscribe to or use the BM Services. If you do not
				want to be bound by the Terms and Conditions, you must not use the
				Website or the BM Services.</p>
				<p>
				 In these Terms, references to "You" or
				"User" or "BMmember" shall mean the end user accessing the
				Website/BMservices, its contents or using the BM Services offered.
				"BM Services" means a collective reference to the Bharat Matrimony
				service provided by Matrimony.com Limited,CIN :
				U63090TN2001PLC047432,a company under the provisions of companies
				act, 2013 and having its registered office at No.94, TVH Beliciaa
				Towers, Tower - 2, 10th Floor, MRC Nagar, Chennai, Tamil Nadu – 600
				028('MCL/Company').</p></div>
	</div>
	</div>
	</div>

<%@ include file="userFooter.jsp"%>