<%@ include file="userStepsHeader.jsp"%>
<%@ include file="homeMenu.jsp"%>
<div class="clearfix"></div>
<img src="nimages/terms.jpg" class="img-responsive" />
<div class="container" style="background: white; padding-top: 25px;">
	<div class="container-fluid">
		<div class="panel panel-success">
			<div class="panel-heading">Terms &amp; Conditions</div>
			<div class="panel-body" style="min-height: 350px;">




				<p align="justify">This document is an electronic record in
					terms of the Information Technology Act, 2000 and rules there under
					pertaining to electronic records as applicable and amended. This
					electronic record is generated by a computer system and does not
					require any physical or digital signatures. This document is
					published in accordance with the provisions of Rule 3 (1) of the
					Information Technology (Intermediaries Guidelines) Rules, 2011 that
					require publishing the rules and regulations, privacy policy and
					the terms and conditions for access or usage of
					
					  <a href="#" style="color:blue;"> www.aarnamatrimony.com</a> (the "Website"). Please read the following
					terms and conditions very carefully as your use of the Website and
					associated BM Services (as defined below) is subject to your
					acceptance of and compliance with the following terms and
					conditions including the applicable policies which are incorporated
					herein by way of reference and as amended from time to time (the
					"Terms and conditions").</p>


			</div>
		</div>
	</div>
	</div>
<%@ include file="homeFooter.jsp"%>